# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-08 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minerador', '0002_auto_20190608_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
