# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-08 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minerador', '0003_auto_20190608_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
