# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-08 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minerador', '0006_auto_20190608_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='installments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
