# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-12 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minerador', '0007_auto_20190608_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Historic Summary',
                'verbose_name_plural': 'Historic Summaries',
                'proxy': True,
            },
            bases=('minerador.history',),
        ),
    ]
